name = 'Silavind'
license = 'GPL-3.0-or-later'
licenselink = 'https://github.com/ertzizart/silavind/LICENSE'
description = 'A minimalist single-page Hugo theme...'
homepage = 'https://github.com/ertzizart/silavind'
demosite = 'https://ertzizart.github.io/silavind/'
tags = ["blog", "responsive", "clean", "light", "dark"]
features = ["blog", "darkmode", "single-column", "responsive"]
min_version = "0.147.0"

[author]
name = 'Hao Wu'
homepage = 'https://ertzizart.com'

